---
title             : "The New Title"
shorttitle        : "The Running Head"

author: 
  - name          : "Akhila Nekkanti"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Postal address"
    email         : "akhilan@uoregon.edu"
  - name          : "Brock Rowley"
    affiliation   : "1"
    corresponding : no
    address       : "Behavioral Research & Teaching (BRT) 175 Lokey Education 5262                                             University of Oregon Eugene, OR, 97403-5262"
    email         : "brockr@uoregon.edu"
  - name          : "Jeff Gau"
    affiliation   : "1"
    corresponding : no
    address       : "College of Education Center on Human Development (chd.uoregon.edu) University Center                      for Excellence in Developmental Disabilities (UCEDD) 901 East 18th Ave, CSB 354                           Eugene, Oregon 97403"
    email         : "jeffg@uoregon.edu"
  - name          : "Kyle Reardon"
    affiliation   : "1"
    corresponding : no
    address       : "Department of Special Education and Clinical Sciences University of Oregon"
    email         : "kreardon@uoregon.edu"
  - name          : "Kyle Reardon"
    affiliation   : "1"
  affiliation:
  - id            : "1"
    institution   : "University of Oregon"
    
abstract: |
  This is our abstract and it's really something else! SO abstract!
  
keywords          : "add, some, keywords, words, keys"

bibliography      : ["r-references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : no
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---
```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      warning = FALSE, 
                      fig.width = 6.5, 
                      fig.height = 8)

library(rio)
library(here)
library(tidyverse)
library("papaja")
library(janitor)
```

```{r import_data}
star <- import(here("data", "star.csv")) %>%  
        janitor::clean_names()
```

```{r analysis-preferences}
# Seed for random number generation
set.seed(42)
knitr::opts_chunk$set(cache.extra = knitr::rand_seed)
```



# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results

# Discussion


\newpage

# References
```{r create_r-references}
r_refs(file = "r-references.bib")
```

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>
\endgroup
